name: nfs4
base: core20
version: '0.1'
summary: Single-line elevator pitch for your amazing snap
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel
confinement: devmode

plugs:
  network-bind:

apps:
  mount:
    command: sbin/mount.nfs
  umount:
    command: sbin/umount.nfs

parts:
  debs:
    plugin: nil
    stage-packages:
      - nfs-common
    prime:
      - lib/$SNAPCRAFT_ARCH_TRIPLET
      - sbin/mount.nfs
      - sbin/umount.nfs
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET
